# Generated by Django 4.0.5 on 2022-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
