# Generated by Django 4.0.5 on 2022-07-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.category'),
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.comment'),
        ),
        migrations.AddField(
            model_name='student',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.post'),
        ),
        migrations.AddField(
            model_name='student',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.wishlist'),
        ),
    ]
