# Generated by Django 4.0.5 on 2022-07-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0005_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.likes'),
        ),
    ]
