# Generated by Django 4.0.5 on 2022-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0006_alter_student_categories_alter_student_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='motivation_app.comment'),
        ),
    ]
