# Generated by Django 4.0.5 on 2022-07-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0005_admin_username'),
        ('motivation_app', '0009_alter_student_user'),
    ]

    operations = [
    ]
