# Generated by Django 4.0.5 on 2022-07-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0007_remove_post_likes_likes_post_id'),
        ('motivation_app', '0010_merge_0005_admin_username_0009_alter_student_user'),
    ]

    operations = [
    ]
