# Generated by Django 4.0.5 on 2022-07-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0007_remove_post_likes_likes_post_id'),
        ('motivation_app', '0011_addedusers'),
    ]

    operations = [
    ]
