# Generated by Django 4.0.5 on 2022-07-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0011_merge_20220709_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='wishlist',
            new_name='wished_item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='child_comment',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.student'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.student'),
        ),
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_comment', models.TextField(null=True)),
                ('date_commented', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.comment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
