# Generated by Django 4.0.5 on 2022-07-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0012_merge_20220705_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addedusers',
        ),
    ]
