# Generated by Django 4.0.5 on 2022-07-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0013_alter_student_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images_uploaded')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
