# Generated by Django 4.0.5 on 2022-07-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0014_bucketlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='wished_item',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.student'),
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
