# Generated by Django 4.0.5 on 2022-07-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0015_remove_student_wished_item_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='student',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='wished_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motivation_app.wishlist'),
        ),
    ]
