# Generated by Django 4.0.5 on 2022-07-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0016_childcomment_date_commented_childcomment_user_id'),
        ('motivation_app', '0016_rename_student_wishlist_student_id_and_more'),
    ]

    operations = [
    ]
